### ISSUE TITLE
HU_001 TA 2  Creación Navbar(Estructura básica Inicio -Servicios-Contacto)---Aplicar css

### ISSUE THREAD

**Issue by ArielRetamales1593** [ArielRetamales1593/Proyecto-Front-end-Matt-Cargo#5]

**Comment by ArielRetamales1593** [comment]
![Image](https://user-images.githubusercontent.com/109328342/228076235-17ac931c-e406-4067-9b60-eafbfe71c6d3.JPG)

**Comment by ArielRetamales1593** [comment]
Hola bárbara ,cómo estai?
Adjunto la referencia del navbar, aún no tengo clara la letra que voy a usar ni el logo pero es más o menos una idea de lo que quiero lograr.
Saludos!

**Comment by ArielRetamales1593** [comment]
es solo el navbar, ignora el dibujo y los títulos c:

**Comment by nathalieCarrasco** [comment]
hola como anotación note que el navbar esta fuera del body no lo quise correr para no chocar con la rama de quien este haciéndolo y haga conflictos pero para que lo revisen

**Comment by Poipurin** [comment]
corregido el posicionamiento de la etiqueta del colaborador desconocido jajaj
